---
deployment:
  tasks:
    - export DEPLOYPATH=/home2/luisyane/api.mundoasiatico.cl
    - /usr/local/bin/php artisan config:clear
    - /usr/local/bin/php artisan route:clear
    - /usr/local/bin/php artisan view:clear
    - /usr/local/bin/php artisan migrate --force
    - /usr/local/bin/php artisan storage:link
